---
title: "3036274164_q3"
author: "PENG, Xin"
date: "2024-04-15"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
setwd("/Users/amypxx/Library/CloudStorage/OneDrive-TheUniversityofHongKong-Connect/adv stat/final exam")
```

# Q3 A 

```{r q3a}
q3<-read.csv("exam_question3.csv")
head(q3)
summary(q3)

table(q3$period)
table(q3$agegp)

pois <- glm(cases~ offset(log(pop)) + period + agegp, 
                 family=poisson, data=q3)
summary(pois)

### incidence per 100,000 population by time period and age groups
q3$incidence<-with(q3,round(cases/pop*100000,2))
q36<-q3[q3$agegp=='6',]
q36<-q36[,c('period','incidence')]
head(q36)
plot(q36$period, q36$incidence,  xlab='period', ylab='incidence', 
     ylim = c(25,310))

```

# Q3 B 

```{r}
q3.time<-aggregate(q3$cases, by=list(q3$period), sum) 
colnames(q3.time) <- c('period', 'cases')

head(q3.time)
plot(q3.time$period, q3.time$cases, type='l', xlab='period', ylab='cases')
```
Before 2002-2006

### Q3C####

```{r}

model5<-glm(poor.bone~low.calc+low.calc*male, data=q3_dat, family=binomial)

model6<-glm(poor.bone~low.calc+low.calc*age, data=q3_dat, family=binomial)

summary(model5)
summary(model6)
```

### Q3D####
```{r}
model7<-glm(poor.bone ~ low.calc + male + phy.index + bmi + low.calc*male, 
            data=q3_dat, family=binomial)

summary(model7)
```
###Q3E####
```{r}
##female
exp(model7$coef["low.calc"])
exp(confint.default(model7)["low.calc",])

##male
exp(model7$coef["low.calc"]+model7$coef["low.calc:male"])

```
###Q3F#####
```{r}
model8<-glm(poor.bone ~ low.calc + male + phy.index  + low.calc*male, 
            data=q3_dat, family=binomial)

new_data <- data.frame(
  low.calc = 1,  
  male = 1,     
  phy.index = 65
)

probability <- predict(model8, newdata = new_data, type = "response")

probability
```